# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='risk_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='risk_type_fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type_id', models.CharField(max_length=100)),
                ('fieldname', models.CharField(max_length=100)),
                ('fieldtype', models.CharField(max_length=100)),
            ],
        ),
    ]
