# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_risk_type_risk_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk_type',
            name='risk_type_id',
        ),
    ]
